#!/bin/sh
set -eu
project_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
: "${SIGNING_IDENTITY:?Set the existing Developer ID Application identity}"
: "${NOTARY_PROFILE:?Set the existing notarytool Keychain profile name}"
dist_dir="$project_dir/dist"
app="$dist_dir/Homebrew Pool.app"
codesign --verify --deep --strict "$app"
mkdir -p "$project_dir/build"
stage=$(mktemp -d "$project_dir/build/notarize-XXXXXX")
ditto -c -k --sequesterRsrc --keepParent "$app" "$stage/submit.zip"
xcrun notarytool submit "$stage/submit.zip" --keychain-profile "$NOTARY_PROFILE" --wait --output-format json > "$stage/app-notarization.json"
python3 -c 'import json,sys; r=json.load(open(sys.argv[1])); print(r); sys.exit(0 if r.get("status")=="Accepted" else 1)' "$stage/app-notarization.json"
xcrun stapler staple "$app"
xcrun stapler validate "$app"
mkdir -p "$stage/dmg"
ditto "$app" "$stage/dmg/Homebrew Pool.app"
ln -s /Applications "$stage/dmg/Applications"
cp "$project_dir/QUICKSTART.txt" "$stage/dmg/Read Me.txt"
dmg="$dist_dir/Homebrew-Intel-Bottle-Pool-v0.3.0.dmg"
hdiutil create -quiet -volname "Homebrew Pool 0.3.0" -srcfolder "$stage/dmg" -ov -format UDZO "$dmg"
codesign --force --timestamp --sign "$SIGNING_IDENTITY" "$dmg"
xcrun notarytool submit "$dmg" --keychain-profile "$NOTARY_PROFILE" --wait --output-format json > "$stage/dmg-notarization.json"
python3 -c 'import json,sys; r=json.load(open(sys.argv[1])); print(r); sys.exit(0 if r.get("status")=="Accepted" else 1)' "$stage/dmg-notarization.json"
xcrun stapler staple "$dmg"
xcrun stapler validate "$dmg"
spctl --assess --type execute --verbose=2 "$app"
spctl --assess --type open --context context:primary-signature --verbose=2 "$dmg"
ditto -c -k --sequesterRsrc --keepParent "$app" "$dist_dir/Homebrew-Intel-Bottle-Pool-v0.3.0.zip"
cp "$stage/app-notarization.json" "$dist_dir/app-notarization.json"
cp "$stage/dmg-notarization.json" "$dist_dir/dmg-notarization.json"
echo "App and DMG accepted, stapled and assessed."
