#!/bin/sh
set -eu
project_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
: "${SIGNING_IDENTITY:?Set the existing Developer ID Application identity}"
: "${NOTARY_PROFILE:?Set the existing notarytool Keychain profile name}"
dist_dir="$project_dir/dist"
app="$dist_dir/Homebrew Pool.app"
python3 "$project_dir/release_checks.py" verify-release "$app"
# The gate above binds the signed app to clean, committed source before submission.
codesign --verify --deep --strict "$app"
mkdir -p "$project_dir/build"
stage=$(mktemp -d "$project_dir/build/notarize-XXXXXX")
ditto -c -k --sequesterRsrc --keepParent "$app" "$stage/submit.zip"
python3 "$project_dir/notary_transport.py" submit "$stage/submit.zip" "$stage/app-notarization.json"
python3 -c 'import json,sys; r=json.load(open(sys.argv[1])); print(r); sys.exit(0 if r.get("status")=="Accepted" else 1)' "$stage/app-notarization.json"
xcrun stapler staple "$app"
xcrun stapler validate "$app"
mkdir -p "$stage/dmg"
ditto "$app" "$stage/dmg/Homebrew Pool.app"
ln -s /Applications "$stage/dmg/Applications"
cp "$project_dir/QUICKSTART.txt" "$stage/dmg/Read Me.txt"
cp "$project_dir/LICENSE" "$stage/dmg/License.txt"
dmg="$dist_dir/Homebrew-Intel-Bottle-Pool-v0.3.5.dmg"
hdiutil create -quiet -volname "Homebrew Pool 0.3.5" -srcfolder "$stage/dmg" -ov -format UDZO "$dmg"
codesign --force --timestamp --sign "$SIGNING_IDENTITY" "$dmg"
python3 "$project_dir/notary_transport.py" submit "$dmg" "$stage/dmg-notarization.json"
python3 -c 'import json,sys; r=json.load(open(sys.argv[1])); print(r); sys.exit(0 if r.get("status")=="Accepted" else 1)' "$stage/dmg-notarization.json"
xcrun stapler staple "$dmg"
xcrun stapler validate "$dmg"
spctl --assess --type execute --verbose=2 "$app"
spctl --assess --type open --context context:primary-signature --verbose=2 "$dmg"
ditto -c -k --sequesterRsrc --keepParent "$app" "$dist_dir/Homebrew-Intel-Bottle-Pool-v0.3.5.zip"
cp "$stage/app-notarization.json" "$dist_dir/app-notarization.json"
cp "$stage/dmg-notarization.json" "$dist_dir/dmg-notarization.json"
app_id=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["id"])' "$stage/app-notarization.json")
dmg_id=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["id"])' "$stage/dmg-notarization.json")
python3 "$project_dir/notary_transport.py" log "$app_id" "$dist_dir/app-notarization-log.json"
python3 "$project_dir/notary_transport.py" log "$dmg_id" "$dist_dir/dmg-notarization-log.json"
python3 "$project_dir/package_release.py"
python3 "$project_dir/verify_distribution.py"
echo "App and DMG accepted, stapled and assessed; containers, documentation and sources verified."
